#!/bin/bash

set -e

# -----------------------------------------------------------------------------
# Applications base dir
#
# <root path>
# * services
#   * gateway
#   * mautic1
#   * mautic2
#   * run
# * apps
#   * mautic1
#   * mautic2
#
base_dir="$(realpath $(dirname "$0"))"
export APPS_DIR="$base_dir/../apps/"

if [[ -f "$base_dir/config.env" ]]; then
	source "$base_dir/config.env"
fi

# -----------------------------------------------------------------------------
# User for containers
export CURRENT_UID="$(id -u):$(id -g)"

###############################################################################

if [[ -z $(docker ps -q --filter "name=^/gateway$") ]]; then
	printf "\e[37mRunning proxy \e[90m... "
	cd "$base_dir/gateway"
	docker-compose -p "$PROXY_NAME" up -d
	sleep 10
	printf "\e[32;1mdone\n"
fi

if [[ -z "$1" ]]; then
	exit 1;
fi

current_app=${1%/}
project="$base_dir/$current_app"
if [[ ! -f "$project/docker-compose.yml" ]]; then
	printf "\e[0mInvalid project name: \e[31;1m%s\n" "$CURRENT_APP"
	exit 1;
fi

cd "$project"
case "$2" in
	env:up)
		docker-compose up -d
		;;

	env:down)
		docker-compose down
		;;

	env:build)
		docker-compose build
		;;

	run:sh)
		docker-compose exec "$3" /bin/bash
		;;

	run:db)
		docker-compose exec db mysql -uroot
		;;

	install:composer)
		docker-compose exec --privileged cli composer install
		;;

	install:npm)
		docker-compose exec --privileged cli npm  install
		;;

	app:cache)
		docker-compose exec --privileged cli php /app/app/console cache:clear
		;;

	app:build)
		docker-compose exec --privileged cli grunt build
		;;
esac	