version: "3"
services:
  gateway:
    image: traefik
    container_name: gateway
    ports:
      - "80:80"
      - "443:443"
    command:
      - "--entrypoints=Name:http Address::80 Redirect.EntryPoint:https"
      - "--entrypoints=Name:https Address::443 TLS"
      - "--defaultentrypoints=http,https"
      - "--insecureskipverify"
      - "--docker"
      - "--docker.watch"
      - "--docker.exposedbydefault=false"
      - "--acme"
      - "--acme.email=${ACME_EMAIL}"
      - "--acme.storage=/acme/storage.json"
      - "--acme.acmelogging"
      - "--acme.onhostrule=true"
      - "--acme.entrypoint=https"
      - "--acme.httpchallenge"
      - "--acme.httpchallenge.entrypoint=http"
      - "--traefiklog"
      - "--loglevel=INFO"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/acme
    restart: always
    networks:
      - gateway

networks:
  gateway:
    ipam:
      driver: default

volumes:
  acme:
