version: '2'
services:
  http:
    build: ./http
    restart: always
    hostname: http
    user: ${CURRENT_UID}
    env_file:
      - ./config.env
    depends_on:
      - fpm
    links:
      - fpm
    volumes:
      - ./http/nginx.conf:/etc/nginx/nginx.conf
      - ./http/default.conf:/etc/nginx/conf.d/default.conf
      - ${APPS_DIR}/mautic:/app
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${PROJECT_DOMAIN}"
      - "traefik.frontend.entryPoints=https"
      - "traefik.protocol=http"
      - "traefik.port=8080"
      - "traefik.docker.network=proxy_gateway"
    networks:
      - default
      - gateway
  cli:
    build: ./cli
    hostname: cli
    privileged: true
    user: ${CURRENT_UID}
    working_dir: /app
    volumes:
      - ./cli/crontab:/crontab/crontab
      - ./cli/php.ini:/usr/local/etc/php/php.ini
      - ~/.composer:/.composer
      - ${APPS_DIR}/mautic:/app
    links:
      - db
    depends_on:
      - db
    networks:
      - default
  fpm:
    build: ./fpm
    restart: always
    user: ${CURRENT_UID}
    working_dir: /app
    depends_on:
      - db
    links:
      - db
    env_file:
      - ./config.env
    volumes:
      - ./fpm/docker.conf:/usr/local/etc/php-fpm.d/docker.conf
      - ./fpm/php.ini:/usr/local/etc/php/php.ini
      - ${APPS_DIR}/mautic:/app
    networks:
      - default
  db:
    image: mariadb
    restart: always
    env_file:
      - ./config.env
    volumes:
      - db-storage:/var/lib/mysql
    networks:
      - default

volumes:
  db-storage:

networks:
  gateway:
    external:
      name: ${PROXY_NAME}_gateway

